name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Test And Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - run: flutter --version
      - uses: subosito/flutter-actions@v1
        with:
          channel: "stable"
      - run: flutter pub get
#      - run: flutter analyze
      - run: flutter test
